defaults:
  - _self_
  - problem: gw_mlgwsc1
  - llm_client: openai
  - override hydra/output: local

hydra:
  job:
    name: ${problem.problem_name}
    chdir: True

# The chosen algorithm
algorithm: evo_mcts

# Main GA loop parameters
max_fe: 1000 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 4 # initial population size for GA
timeout: 180 # timeout for evaluation of a single heuristic
debug_mode: False
use_seed: False

# Resume directories (optional)
resume_dirs: [] # list of directories to resume from